# Generated by Django 5.0.4 on 2024-04-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_askqa'),
    ]

    operations = [
        migrations.AddField(
            model_name='askqa',
            name='detail_answer',
            field=models.TextField(blank=True, null=True, verbose_name='คำตอบ'),
        ),
    ]
