# Generated by Django 5.0.4 on 2024-04-20 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_author_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='images',
        ),
    ]
